### ISSUE TITLE
Bootstrap modals inside c-offcanvas-content-wrap creates two backdrops

### ISSUE THREAD

**Issue by TheTimeWalker** [vmitsaras/js-offcanvas#33]
There seems to be an issue with modals being inside an div with class c-offcanvas-content-wrap. Whenever a modal that's inside the class is being opened up, it creates two backdrops.

Both are from the modal backdrop and the canvas backdrop and closing the modal only removes one backdrop, being essentially stuck with a dark background.

Here's a Codepen example: https://codepen.io/anon/pen/djWgbY
Just click on "Launch demo modal"

This was mentioned in an closed issue here: https://github.com/vmitsaras/js-offcanvas/issues/18#issuecomment-387348229

**Comment by vmitsaras** [comment]
a quick fix for this 
```css
.modal-open .c-offcanvas-content-wrap {
 -webkit-transform:none;
    transform: none;
    position: static;
}
```
