### ISSUE TITLE
speed of animation

### ISSUE THREAD

**Issue by cekvenich** [vmitsaras/js-offcanvas#34]
Is there a way to make the open faster?

I looked at docs and can't see it.

ps: we use this at metabake.org

**Comment by vmitsaras** [comment]
You have to change the CSS. 
#### Default
```css
.c-offcanvas {
    transition: transform 300ms cubic-bezier(0.4, 0, 0.6, 1);
}
```
#### Change the duration 
```css
.c-offcanvas {
     transition-duration: 150ms;
}
```

**Comment by cekvenich** [comment]
Worked, thx. I used 200ms.

(you can see the projects at Metabake.org)

**Comment by vmitsaras** [comment]
OK.
I can't find the offcanvas on metabake

**Comment by cekvenich** [comment]
One example web app: https://github.com/metabake/front-end-frameworks/tree/master/fullPage

but if you want more examples, there are 5, including SPA phonegap:
npm -g i mbake
mbake

**Comment by vmitsaras** [comment]
I am glad I was able to help you.

**Comment by manchumahara** [comment]
@vmitsaras any idea how to control the speed when closes the off canvas ?

**Comment by vmitsaras** [comment]
Hi @manchumahara,
you can use the [.c-offcanvas--closing](https://github.com/vmitsaras/js-offcanvas/blob/master/dist/_css/js-offcanvas.css#L8) class to control the speed/duration

```css
.c-offcanvas--closing {
    transition-duration: .7s;
    transition-timing-function: cubic-bezier(0.4, 0.0, 1, 1)
}
```

Some Info: https://material.io/design/motion/speed.html#easing
