### ISSUE TITLE
Fade out background when closing

### ISSUE THREAD

**Issue by TheTimeWalker** [vmitsaras/js-offcanvas#36]
A small suggestion, when closing overlays, the background pops from black to transparent which looks a bit jarring. Just like how the background fades in when opening, it would be nice if it fades out when closing overlays.

Currently, a hackish way to accomplish this is by adding a small CSS snippet:
```css
.c-offcanvas-bg.is-animating.is-open {
    background: rgba(0, 0, 0, 0.68);
}

.c-offcanvas-bg.is-animating {
    background: none;
}
```

I think the best way would be however to replace `is-animating` with two classes called `is-opening` and `is-closing`
