### ISSUE TITLE
Set "speed"

### ISSUE THREAD

**Issue by cfoellmann** [vmitsaras/js-offcanvas#56]
Is it possible to set a value for the speed of the "push in"?

**Comment by vmitsaras** [comment]
Hi @cfoellmann,

you can change the value (300ms) in css

``` css
.c-offcanvas-bg.c-offcanvas-bg--push, .c-offcanvas-bg.c-offcanvas-bg--reveal, .c-offcanvas-content-wrap, .c-offcanvas {
  transition: transform 300ms cubic-bezier(0.4, 0, 0.6, 1);
}

.c-offcanvas-bg.c-offcanvas-bg--push, .c-offcanvas-bg.c-offcanvas-bg--reveal, .c-offcanvas-content-wrap, .c-offcanvas {
  transition-duration: 300ms;
}

```
